name: 'Pull Request'
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Installation
        run: npm install
      - name: Lint and Prettier
        run: npm run lint && npm run prettier:check
      - name: Type Check
        run: npm run types:check
      - name: Unit Tests
        run: npm run test